// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

// Injectors from wire_inject.go:

func SetupApplication() (Application, error) {
	context := ProvideContext()
	logger, err := ProvideLogger()
	if err != nil {
		return Application{}, err
	}
	server, err := ProvideHTTPServer(logger)
	if err != nil {
		return Application{}, err
	}
	grpcServer, err := ProvideGRPCServer(logger)
	if err != nil {
		return Application{}, err
	}
	application := NewApplication(context, logger, server, grpcServer)
	return application, nil
}
